# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'El Pregonero' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for El Pregonero

pod 'Alamofire' 
pod 'Kingfisher'

  target 'El PregoneroTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'El PregoneroUITests' do
    # Pods for testing
  end

end
